[package]
name = "foxbox_taxonomy"
version = "0.1.2"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]

[dependencies]
chrono = "0.2.19"
clippy = "0.0.48"
lazy_static = "^0.1"
libc = "0.2.9"
rusqlite = "0.6.0"
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
string_cache = "^0.2"
sublock = "^0.1"
transformable_channels = "^0.1"
